name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.18
main: org.sucraft.portabletoolblocks.main.SuCraftPortableToolBlocksPlugin
depend: [SuCraft-Core]
commands:
  craftingtable:
    description: Open the portable crafting table
    aliases: [workbench, wo, wb, craft, crafttable]
    permission: sucraft.portabletoolblocks.craftingtable
  enderchest:
    description: Open the portable ender chest
    aliases: [endchest, echest]
    permission: sucraft.portabletoolblocks.enderchest
permissions:
  sucraft.portabletoolblocks.craftingtable:
    description: Use the craftingtable command
    default: op
  sucraft.portabletoolblocks.enderchest:
    description: Use the enderchest command
    default: op
  sucraft.portabletoolblocks.enderchest.other:
    description: Open the ender chest of other players
    default: op