name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.uuidcommand.main.SuCraftUUIDCommandPlugin
depend: [SuCraft-Core]
commands:
  uuid:
    description: See the UUID of a player
    permission: sucraft.uuidcommand.uuid
permissions:
  sucraft.uuidcommand.uuid:
    description: Use the uuid command
    default: op