name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.discordinfo.main.SuCraftDiscordInfoPlugin
depend: [SuCraft-Core]
commands:
  discord:
    description: See the Discord server link
    permission: sucraft.discordinfo.discord
permissions:
  sucraft.discordinfo.discord:
    description: Use the discord command
    default: true