name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.unsignbooks.main.SuCraftUnsignBooksPlugin
depend: [SuCraft-Core]
commands:
  unsign:
    description: Unsign a book
    aliases: [unsignbook]
    permission: sucraft.unsignbooks.unsign.own
permissions:
  sucraft.unsignbooks.unsign.own:
    description: Unsign own books
    default: true
  sucraft.unsignbooks.unsign.other:
    description: Unsign other people's books
    default: op
