name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.eastereggcommand.main.SuCraftEasterEggCommandPlugin
depend: [SuCraft-Core]
commands:
  easteregg:
    description: There is nothing here
    permission: sucraft.eastereggcommand.easteregg
permissions:
  sucraft.eastereggcommand.easteregg:
    description: Use the easteregg command
    default: true