name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.18
main: org.sucraft.monsterfreeareas.main.SuCraftMonsterFreeAreasPlugin
depend: [SuCraft-Core]
