name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.18
main: org.sucraft.mysteryboxes.main.SuCraftMysteryBoxesPlugin
depend: [SuCraft-Core, SuCraft-Supporters]
commands:
  mysterybox:
    description: Hide the contents of a shulker box
    aliases: [createmysterybox, shulkermysterybox, mysteryshulkerbox]
permissions:
  sucraft.mysteryboxes.create:
    description: Use the mysterybox command
    default: op