name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.broadcast.main.SuCraftBroadcastPlugin
depend: [SuCraft-Core, SuCraft-DiscordInfo]
permissions:
  sucraft.broadcast.ignore:
    description: Receive no broadcasted messages
    default: false
