name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.lightningcommand.main.SuCraftLightningCommandPlugin
depend: [SuCraft-Core]
commands:
  lightning:
    description: Strike decorative lightning
    aliases: [lightningbolt]
permissions:
  sucraft.lightningcommand.lightning:
    description: Use the lightning command
    default: op