name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.zombiehorses.main.SuCraftZombieHorsesPlugin
depend: [SuCraft-Core, SuCraft-CustomJockeys]
