name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.18
main: org.sucraft.opmecommand.main.SuCraftOpMeCommandPlugin
depend: [SuCraft-Core]
commands:
  opme:
    description: Become Moderator
    permission: sucraft.opmecommand.opme
permissions:
  sucraft.opmecommand.opme:
    description: Use the opme command
    default: true