name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.18
main: org.sucraft.antilag.main.SuCraftAntiLagPlugin
depend: [SuCraft-Core, SuCraft-MeasureTPS, SuCraft-TemporaryMobFarmLimits, FartherViewDistance]
