name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.supporters.main.SuCraftSupportersPlugin
depend: [SuCraft-Core, SuCraft-DiscordInfo]
