name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.18
main: org.sucraft.itemsonhead.main.SuCraftItemsOnHeadPlugin
depend: [SuCraft-Core, SuCraft-Supporters]
commands:
  head:
    description: Put an item or block on your head
    aliases: [hat, sethat, helmet, sethelmet, sethead]
permissions:
  sucraft.itemsonhead.all:
    description: Use the head command for all items
    default: op
  sucraft.itemsonhead.helmet:
    description: Use the head command for helmets
    default: true
  sucraft.itemsonhead.banner:
    description: Use the head command for banners
    default: true