name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${pluginDescriptionAuthor}
website: ${pluginDescriptionWebsite}
api-version: 1.17
main: org.sucraft.playercompass.main.SuCraftPlayerCompassPlugin
depend: [SuCraft-Core, SuCraft-Supporters]
commands:
  playercompass:
    description: Create a compass that points to you
    aliases: [trackercompass, pointercompass]
permissions:
  sucraft.playercompass.create:
    description: Use the playercompass command
    default: op